main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Teaching
    url: /#teaching
    weight: 30
  - name: Search
    url: /search/
    weight: 50
  - name: CV
    url: /uploads/cv.pdf
    weight: 60
