main:
  - name: Hjem
    url: /
    weight: 10
  - name: Forskning
    url: /#forskning
    weight: 20
  - name: Blog
    url: https://gavinsdavies.com/blog/
    weight: 30
  - name: Søg
    url: /search/
    weight: 40
  - name: CV
    url: https://gavinsdavies.com/uploads/cv.pdf
    weight: 50
