env: production
description: Experimental particle physicist at the University of Mississippi working on neutrino oscillation physics with NOvA, DUNE, and EMPHATIC.
author: Gavin S. Davies
defaultTheme: auto
ShowReadingTime: true
ShowShareButtons: false
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowToc: true
TocOpen: false
hideFooter: false

assets:
  favicon: /img/gsd-memoji.svg

label:
  text: Gavin S. Davies
  icon: /img/gsd-memoji.svg
  iconHeight: 28

profileMode:
  enabled: true
  title: Gavin S. Davies
  subtitle: Associate Professor of Physics & Astronomy at the University of Mississippi, working on neutrino oscillations with NOvA, DUNE, and EMPHATIC.
  imageUrl: /img/me.jpg
  imageTitle: Gavin S. Davies
  imageWidth: 160
  imageHeight: 160
  buttons:
    - name: Research Group
      url: https://www.umneutrino.org
    - name: CV
      url: /uploads/cv.pdf

socialIcons:
  - name: email
    url: mailto:gsdavies@olemiss.edu
  - name: github
    url: https://github.com/gavinsdavies
  - name: linkedin
    url: https://www.linkedin.com/in/gavinsdavies
  - name: orcid
    url: https://orcid.org/0000-0002-5728-5356
  - name: googlescholar
    url: https://scholar.google.com/citations?user=Yg5rE2YAAAAJ
  - name: inspire
    title: Inspire-HEP
    url: https://inspirehep.net/authors/1068224

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 2
  keys:
    - title
    - permalink
    - summary
    - content
