[build]
  command = "npm install && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.162.1"
  HUGO_ENVIRONMENT = "production"
  NODE_VERSION = "22"
  TZ = "America/Chicago"

[context.deploy-preview]
  command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"
